{% set name = "hip" %}
{% set version = "7.2.4" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}
{% set major_minor_version = ".".join(version.split(".")[:2]) %}
{% set patch_version = version.split('.')[2] %}
{% set llvm_major_version = "22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ROCm/rocm-systems/releases/download/rocm-{{ version }}/hip.tar.gz
    sha256: 76c3d6909e531f30b84c908984891559d221d8c427d44abc88be5dbb123f9ad6
    folder: hip

  - url: https://github.com/ROCm/rocm-systems/releases/download/rocm-{{ version }}/clr.tar.gz
    sha256: c9670697ee47b2d33dde84e4c815a62f594061da9ff184b133b87a227a1a1f02
    folder: clr
    patches:
      - 0001-Mark-raw-strings.patch
      - 0002-Use-major-version-for-library-VERSION.patch

  - url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: 526b5fe23417c41acbeb2273e470887b4593f48a297a8d9c1a1aa730d556f9fb
    folder: hipcc
    patches:
      - 0003-Fix-cmake-backward-compatibility.patch
      - 0004-hipcc-path.diff

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - cppheaderparser
    - wget
    - python *
  host:
    - clangdev {{ llvm_major_version }}.*
    - numactl
    - llvmdev {{ llvm_major_version }}.*
    - ocl-icd
    - rocm-core {{ version }}.*
    - rocm-comgr {{ major_minor_version }}.*
    - rocr-runtime {{ major_minor_version }}.*
    - rocm-cmake {{ major_minor_version }}.*
    - zlib
    - rocminfo {{ major_minor_version }}.*
    - libgl-devel
    - libopengl-devel
    - libglx-devel
    - libegl-devel

outputs:
  - name: hip-runtime-amd
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-core {{ version }}.*
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
      run:
        - libnuma  # to work around missing run_exports in numactl
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
    files:
      - lib/.hipInfo
      - lib/cmake/hip/hip-targets*.cmake
      - lib/cmake/hip-lang/*.cmake
      - lib/cmake/hiprtc/*.cmake
      - lib/libamdhip64.so*
      - lib/libhiprtc.so*
      - lib/libhiprtc-builtins.so*
      - share/doc/hip/LICENSE.md
    test:
      commands:
        - test -f $PREFIX/lib/.hipInfo
        - test -f $PREFIX/lib/libamdhip64.so
        - test -f $PREFIX/lib/libamdhip64.so.{{ major_version }}

  - name: hip-devel
    requirements:
      run:
        - {{ pin_subpackage("hip-runtime-amd") }}
    run_exports:
      - {{ pin_subpackage("hip-runtime-amd") }}
    files:
      - bin/hipcc_cmake_linker_helper
      - bin/hipdemangleatp
      - bin/roc-obj
      - bin/roc-obj-extract
      - bin/roc-obj-ls
      - include/hip/amd_detail/*
      - include/hip/*.h
      - lib/cmake/hip/FindHIP.cmake
      - lib/cmake/hip/FindHIP/*.cmake
      - lib/cmake/hip/hip-config*.cmake
      - share/hip/version
    test:
      commands:
        - test -f $PREFIX/share/hip/version
        - test -f $PREFIX/lib/cmake/hip/FindHIP.cmake
        - test -f $PREFIX/include/hip/hip_common.h

  - name: hipcc
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("hip-devel", exact=True) }}
      run:
        - {{ pin_subpackage("hip-devel", exact=True) }}
        - clang {{ llvm_major_version }}.*
        - clangxx {{ llvm_major_version }}.*
        - llvm-tools {{ llvm_major_version }}.*
        - perl
        - python *
        - rocm-core {{ version }}.*
        - rocminfo {{ major_minor_version }}.*
        # rocm-device-libs, lld and clang-tools are required for HIP compilation
        - rocm-device-libs {{ major_minor_version }}.*
        - lld {{ llvm_major_version }}.*
        - clang-tools {{ llvm_major_version }}.*
        - compiler-rt {{ llvm_major_version }}.*
    files:
      - bin/hipcc
      - bin/hipcc.bin
      - bin/hipcc.pl
      - bin/hipconfig*
      - bin/hipvars.pm
      - share/doc/hipcc/*
      - etc/conda/activate.d/hip_activate.sh
      - etc/conda/deactivate.d/hip_deactivate.sh
    test:
      commands:
        - export HIP_PLATFORM=amd
        - $PREFIX/bin/hipcc --offload-arch=gfx803 --version
        - $PREFIX/bin/hipconfig
        - hipcc --offload-arch=gfx942 ./test/test_cmake_enable_hip/main_hip_smoke_test.hip
      files:
        - test

  # This package provides the files and activation scripts needed to compile HIP code
  # inside conda-build and rattler-build using {{ compiler('hip') }} and targeting the
  # amd/rocm HIP platform
  - name: hip-rocm-clang_linux-64
    requirements:
      run:
        - {{ pin_subpackage("hipcc", exact=True) }}
    run_exports:
      strong:
        - rocm-core {{ major_minor_version }}.*
        - {{ pin_subpackage("hip-runtime-amd") }}
    files:
      - etc/conda/activate.d/hip-rocm-clang_activate.sh
      - etc/conda/deactivate.d/hip-rocm-clang_deactivate.sh
    test:
      commands:
        - cmake-package-check hip --targets hip::host hip::device
        - cmake -B./test/test_cmake_enable_hip_build -S./test/test_cmake_enable_hip -GNinja
        - hipcc --offload-arch=gfx942 ./test/test_cmake_enable_hip/main_hip_smoke_test.hip
        - $HIPCXX --version
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - test

  # This metapackage provides the compiler outside conda-build and rattler-build.
  - name: hip-compiler
    requirements:
      run:
        - {{ pin_subpackage("hip-clang_linux-64", exact=True) }}
    test:
      commands:
        - cmake-package-check hip --targets hip::host hip::device
        - cmake -B./test/test_cmake_enable_hip_build -S./test/test_cmake_enable_hip -GNinja
        - hipcc --offload-arch=gfx942 ./test/test_cmake_enable_hip/main_hip_smoke_test.hip
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - test

  - name: rocm-opencl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-core {{ version }}.*
        - rocm-comgr {{ version }}.*
        - rocr-runtime {{ version }}.*
      run:
        - {{ pin_compatible("rocm-comgr") }}
        - {{ pin_compatible("rocr-runtime") }}
        - libnuma
    files:
      - lib/libamdocl64.so*
      - share/doc/opencl/LICENSE.txt
    test:
      commands:
        - test -f $PREFIX/lib/libamdocl64.so

  - name: rocm-opencl-runtime
    requirements:
      run:
        - {{ pin_subpackage("rocm-opencl", exact=True) }}
        - ocl-icd                 # [linux]
        - khronos-ocl-icd-loader  # [not linux]
    files:
      - etc/OpenCL/vendors/amdocl64.icd
    test:
      commands:
        - test -f $PREFIX/etc/OpenCL/vendors/amdocl64.icd

about:
  home: https://github.com/ROCm/HIP
  license: NCSA
  license_family: MIT
  license_file:
    - clr/LICENSE.md
    - hip/LICENSE.md
    - hipcc/amd/hipcc/LICENSE.txt
  summary: 'HIP: C++ Heterogeneous-Compute Interface for Portability '

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
